### ISSUE TITLE
fastapi-cli clobbers fastapi

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/fastapi-feedstock#138]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/noarch::fastapi-cli-0.0.5-pyhd8ed1ab_1, conda-forge/noarch::fastapi-0.115.2-pyhd8ed1ab_0
  path: 'bin/fastapi'

### Installed packages

You should:

* Patch away the entry point from fastapi

### Environment info

or you could add fastapi-cli to the host section so that it won't detect a new binary file, but I think you should patch fastapi instead.

**Comment by bollwyvl** [comment]
Yep, just got bit by this: PR up on https://github.com/conda-forge/fastapi-feedstock/pull/141

**Comment by davidbrochart** [comment]
I'm not sure this is related to this issue, but:
```bash
micromamba install fastapi
```
prints:
```
warning  libmamba [fastapi-cli-0.0.20-pyhcf101f3_0] The following files were already present in the environment:
    - bin/fastapi
```
Since the `fastapi` entry point is already defined in [fastapi-cli](https://github.com/conda-forge/fastapi-cli-feedstock/blob/164f9b21971d29e6a9f0cbf10029b43ce0b7f5ba/recipe/recipe.yaml#L21), should the one in [fastapi](https://github.com/conda-forge/fastapi-feedstock/blob/f21170ea8601f8d39fcdc02dc37db57d7eb2a3ca/recipe/recipe.yaml#L31) be removed?

**Comment by bollwyvl** [comment]
yep, that's it, pr incoming, not easy to patch for historic versions unfortunately.
